
$(function() {

    // Populate using an object literal
    
    WTF.init({
     heading: [
                "Let me tell you what happened...",
                "Check this shit out,",
                "You had a wild night? Let me tell you about my night!",
                "So remember when I said I haven't had sex in a while...",
                "Dude, you won't believe this!",
                "There I was at the bar when...",
                "I'm telling you, this really happened...",
                "Nobody is going to believe me...",
                "So, there I was when...",
                "Don't laugh but...",
                "People are going to think I'm a pervert because...",
                "I mean, not to brag, but...",
                "I saw your mom and she caught me...",
                "This happened, ask your mom, she was there when...",
            ],
            response: [
                "I need a cold shower now.",
                "Get your mind out of the gutter!",
                "Pardon me, I've got a hot flash coming on...",
                "I feel like a sinner in church!",
                "Good gravy!",
                "I swear I'm not a whore",
                "I can do better",
                "Oh! And then there was that time...",
                "I'm not lying!",
                "It was hot!",
                "It was amazing!",
                "Try to beat that!",
            ],
    
            template: [
                "A @adjective @creature @verbed and @verbed me last night!",
                "I was caught @verbing the @adjective @loveinterest at @place!",
                "A @adjective @loveinterest stuck their @privatepart in my @privatepart!",
                "Author @author wrote a smutty erotica about me @verbing a @adjective @person! How cool!",
                "@loveinterest came through the door and @verbed me like a @adjective harlot!",
                "I was taken to @place and there @loveinterest @verbed me with their @bodypart!",
                "I was reading a book by @author when @loveinterest appeared and @verbed me!",
                "Can you believe I found my name in Author @author's latest book about me @verbing a @adjective @creature!",
                "@author's @adjective @person @verbed my @privatepart in the @locations.",
                "What is with @author and writing about the @privatepart? I swear they write about it a lot, but I prefer the @privatepart as long as it can be @verbed by a @creature!",
                "I met with @loveinterest. Honestly, I really like it when they @verb my @bodypart after @verbing my @privatepart. It was so good!",
                "@loveinterest made @adjective love to me last night. I'll never forget how their @bodypart touched my @privatepart.",
                "I'll never be the same after a @creature woke me up by @verbing my @privatepart!",
                "Have you ever had someone @verb your @bodypart? I have! After a @adjective @creature showed up in my @locations!",
            ],
    
            author: [
                "Honey Cummings",
                "Ali Whippe",
                "Grayson Ace",
                "Leo Sparx",
                "Dalia Lance",
                "Randy Cloose",
                "Chastity Veldt",
                "Beau Lake",
                "V.C. Willis",
                "Shae Coon",
                "Aria Skylar",
            ],
            
            adjective: [
                "bitchy",
                "blunt",
                "boisterous",
                "bossy",
                "brave",
                "callous",
                "cautious",
                "charming",
                "cheerful",
                "churlish",
                "cold",
                "composed",
                "conceited",
                "condescending",
                "confident",
                "conscientious",
                "courageous",
                "crass",
                "critical",
                "cunning",
                "curious",
                "cynical",
                "decisive",
                "dependable",
                "determined",
                "driven",
                "fearless",
                "flamboyant",
                "flirtatious",
                "friendly",
                "gruff",
                "headstrong",
                "hot-headed",
                "lazy",
                "loud",
                "Machiavellian",
                "moody",
                "philosophical",
                "pompous",
                "pretty",
                "romantic",
                "selfish",
                "sensitive",
                "thoughtful",
                "delightful",
                "demure",
                "diligent",
                "disruptive",
                "dramatic",
                "dutiful",
                "frank",
                "funny",
                "fussy",
                "generous",
                "gentle",
                "grouchy",
                "guarded",
                "helpful",
                "hot-headed",
                "hypercritical",
                "level-headed",
                "mean",
                "methodical",
                "meticulous",
                "miserable",
                "motivated",
                "naive",
                "nosy",
                "pensive",
                "playful",
                "plucky",
                "proud",
                "quick-tempered",
                "reliable",
                "resourceful",
                "respectful",
                "restless",
                "sassy",
                "sentimental",
                "short-tempered",
                "sophisticated",
                "spiteful",
                "stoic",
                "sweet",
                "suspicious",
                "talented",
                "warm-hearted",
                "adventurous",
                "agreeable",
                "ambitious",
                "anxious",
                "apathetic",
                "argumentative",
                "assertive",
                "attentive",
                "impulsive",
                "inventive",
                "unpredictable",
                "easy-going",
                "egotistical",
                "emotional",
                "enterprising",
                "enthusiastic",
                "excitable",
                "impatient",
                "impetuous",
                "obnoxious",
                "old-fashioned",
                "outgoing",
                "outspoken",
                "melodramatic",
                "chipper",
                "compassionate",
                "considerate",
                "faithful",
                "modest",
                "naked",
                "sexy",
                "sultry",
                "handsome",
                "gorgeous",
                "horny",
                "raunchy",
                "erotic",
                "sexy",
            ],
    
            person: [
                "Professor",
                "Bouncer",
                "Chef",
                "Billionnaire",
                "Bodyguard",
                "Bartender",
                "Guber Driver",
                "Biker",
                "Prince",
                "Priest",
                "Archbishop",
                "Blacksmith",
                "Princess",
                "Janitor",
                "Comedian",
                "Yoga Instructor",
                "Champion",
                "Organ Player",
                "Viceroy",
                "King",
                "Queen",
                "Assassin",
                "Knight",
            ],
            
            
            creature: [
                "Chupacabra",
                "Sasquatch",
                "Bigfoot",
                "Skunk Ape",
                "Yeti",
                "Jersey Devil",
                "Leprachaun",
                "Faerie",
                "Mermaid",
                "Siren",
                "Minotaur",
                "Incubus",
                "Succubus",
                "Demon",
                "Vampire",
                "Bloodeater",
                "Troll",
                "Werewolf",
                "Ghost",
                "Puckwedgie",
                "Daemon",
                "Wolf-shifter",
                "Wizard",
                "Warlock",
                "God",
                "Demigod",
                "Phantom",
                "Poltrigeist",
            ],

            loveinterest: [
                "Blue Lady",
                "Woman in White",
                "Bloody Mary",
                "Dante",
                "John",
                "Cedric",
                "Tony",
                "Lillith",
                "Hunter",
                "Angus",
                "Red",
                "Goldie",
                "Peter von Schmidt",
                "Professor Bestialora",
                "Beau",
                "Angeline",
                "Alecto",
                "Pan",
                "Boto",
                "Sheriff Jakob R.",
            ],
    
            verbed: [
                "kissed",
                "hugged",
                "groped",
                "licked",
                "touched",
                "goosed",
                "fingered",
                "banged",
                "fucked",
                "bit",
            ],
            
            verbing: [
                "kissing",
                "hugging",
                "groping",
                "licking",
                "touching",
                "goosing",
                "fingering",
                "banging",
                "fucking",
                "biting",
            ],
            
                   
            verb: [
                "kiss",
                "hug",
                "grope",
                "lick",
                "touch",
                "goose",
                "finger",
                "bang",
                "fuck",
                "bite",
            ],
            
            bodypart: [
                "tongue",
                "ear",
                "mouth",
                "finger",
                "hand",
                "foot",
                "fingers",
                "toe",
                "toes",
                "leg",
                "lips",
            ],
            

            privatepart: [
                "pussy",
                "cock",
                "dick",
                "devil's doorbell",
                "penis",
                "starfish",
                "penis",
                "pink pearl",
                "pink valley",
            ],
            
            place: [
                "Red's bar",
                "Lion's Den",
                "Honey Pot Club",
                "Lillith's apartment",
                "Avalon",
                "XTC College",
                "Frey's castle",
            ],

            locations: [
                "closet",
                "office",
                "garage",
                "bed",
                "boat",
                "canoe",
                "car",
                "movie theater",
                "classroom",
                "teacher's office",
                "jailhouse",
                "library",
                "bathhouse",
                "locker room",
                "glory hole",
            ],
     });
    
    });
