
$(function() {

// Populate using an object literal

WTF.init({

heading: [
			"Let me tell you what happened last night...",
			"Check this shit out,",
			"You had a wild night? Let me tell you about my night!",
			"So remember when I said I haven't had sex in a while...",
			"Dude, you won't believe this!",
			"There I was at the bar when...",
			"So, there I was when...",
			"This book I got, man, so the plot is...",
			"I pulled a book off the shelf to read about...",
			"This book is about you and that time when...",
			"Ran into you Mom and guess what she did last night?",
			"Fanning myself after I saw...",
],

   response: [
		  "I need a cold shower now.",
			"Get your mind out of the gutter!",
			"Pardon me, I've got a hot flash coming on...",
			"I feel like a sinner in church!",
			"Good gravy!",
	   		"Is it hot in here?",
	   		"I think I need help!",
	   		"Talk about a thirst trap!",
	   		"But you didn't hear it from me!",
	   		"Shh... this is our little secret...",
	   		"Or so you Mom told me...",
	   		"Who else needs a tumble in the sheets after that one?",
],


template: [
			"The @adjective @loveinterest @verbed and @verbed me!",
			"I was caught @verbing the @adjective @loveinterest in the @locations!",
			"A @adjective @loveinterest @verbing their @bodypart on/in my @bodypart!",
			"Author @author wrote a smutty erotica about me @verbing a @adjective @loveinterest! How cool!",
			"Once upon a time, a @adjective @loveinterest was born with a @adjective @bodypart. When they saw you, they instantly knew you were the one! The one they would @verb for the rest of their life! The End!",
            "Their @bodypart (s) had met in @noun, in @fluid, frantic to get under that thin film with a @bodypart or a @bodypart, as if they each could grip character there and during love pull it right off the body of the other.",
            "I was hers. She was mine. My @bodypart was her @noun, and she @verbed it into the @location. Her @bodypart was my @noun, and I became the @location.",
            "He was careful not to @verb her. She could feel how @adjective she felt to him. She could feel herself through him. Her @bodpart. The way her @bodypart existed only where he @verbed her. The rest of her was @noun.",
            "And I mean to hear ye @verb like that again. And to @verb and @verb, even though you dinna wish to, for ye canna help it. I mean to make you @verb as though your @bodypart would break, and @verb with the wanting, and at last to cry out in my @bodypart, and I shall know that I’ve served ye well.",
],

author: [
			"Honey Cummings",
			"Ali Whippe",
			"Grayson Ace",
			"Leo Sparx",
			"Dalia Lance",
			"Raymond Cloose",
			"Chastity Veldt",
  		    "Dominic Ashen",
 		    "Nova Embers",
		],
		
	adjective: [
				"bigoted",
				"bitchy",
				"blunt",
				"boisterous",
				"bossy",
				"brave",
				"callous",
				"cautious",
				"charming",
				"cheerful",
				"churlish",
				"cold",
				"composed",
				"conceited",
				"condescending",
				"confident",
				"conscientious",
				"cool-headed",
				"courageous",
				"crabby",
				"crass",
				"critical",
				"cruel",
				"cunning",
				"curious",
				"cynical",
				"decisive",
				"dependable",
				"determined",
				"driven",
				"fearless",
				"flamboyant",
				"flirtatious",
				"friendly",
				"gruff",
				"headstrong",
				"hot-headed",
                "thirsty",
                "hungry",
				"lazy",
				"loud",
				"Machiavellian",
				"moody",
				"philosophical",
				"pompous",
				"pretty chill",
				"romantic",
				"selfish",
				"sensitive",
				"tactless",
				"thoughtful",
				"wary",
				"depressed",
				"delightful",
				"demure",
				"diligent",
				"disruptive",
				"discerning",
				"dramatic",
				"dutiful",
				"frank",
				"funny",
				"fussy",
				"generous",
				"gentle",
				"gloomy",
				"grave",
				"grouchy",
				"guarded",
				"hateful",
				"helpful",
				"hot-headed",
				"hypercritical",
				"level-headed",
				"mean",
				"methodical",
				"meticulous",
				"miserable",
				"motivated",
				"morose",
				"naive",
				"nosy",
				"peaceful",
				"pensive",
				"plain-speaking",
				"playful",
				"plucky",
				"positive",
				"proud",
				"prejudiced",
				"quick-tempered",
				"reliable",
				"reluctant",
				"resentful",
				"resourceful",
				"respectful",
				"restless",
				"sassy",
				"sentimental",
				"short-tempered",
				"snobby",
				"sombre",
				"sophisticated",
				"spiteful",
				"soulless",
				"stern",
				"stoic",
				"surly",
				"sweet",
				"suspicious",
				"talented",
				"warm-hearted",
				"wary",
				"well-intentioned",
				"adventurous",
				"agreeable",
				"ambitious",
				"anxious",
				"apathetic",
				"argumentative",
				"assertive",
				"attentive",
				"impulsive",
				"intolerant",
				"inventive",
				"overemotional",
				"unpredictable",
				"eager",
				"easy-going",
				"egotistical",
				"emotional",
				"enterprising",
				"enthusiastic",
				"excitable",
				"impatient",
				"impetuous",
				"inconsiderate",
				"insensitive",
				"irritable",
				"obnoxious",
				"old-fashioned",
				"outgoing",
				"outspoken",
				"unbalanced",
				"unstable",
				"absent minded",
				"melodramatic",
				"paranoid",
				"chipper",
				"passive-aggressive",
				"amicable",
				"broad-minded",
				"compassionate",
				"considerate",
				"diplomatic",
				"faithful",
				"hard-working",
				"modest",
				"naked",
				"sexy",
        "soft",
		"sultry",
		"handsome",
		"gorgeous",
		"massive",
        "enormous",
				
],

loveinterest: [
"Professor",
			"Bouncer",
			"Chef",
			"Chupacabra",
			"Sasquatch",
			"Bigfoot",
			"Skunk Ape",
			"Blue Lady",
			"Woman in White",
			"Bloody Mary",
			"Yeti",
			"Jersey Devil",
			"Leprachaun",
			"Faerie",
			"Mermaid",
			"Siren",
			"Minotaur",
			"Billionnaire",
			"Bodyguard",
			"Bartender",
			"Guber Driver",
			"Biker",
			"Prince",
			"Priest",
			"Archbishop",
			"Blacksmith",
			"Princess",
			"Janitor",
			"Comedian",
			"Yoga Instructor",
			"Dante",
			"John",
			"Cedric",
			"Incubus",
			"Succubus",
			"Demon",
			"Vampire",
			"Bloodeater",
			"Champion",
			"Troll",
			"Wolf",
			"Big Bad Wolf",
			"Red",
			"Goldie",
			"Peter von Schmidt",
			"Organ Player",
			"Orc",
			"Captain",
			"Succubus",
			"Incubus",
			"Mothman",
],

verbed: [
"kissed",
			"hugged",
			"groped",
			"licked",
			"touched",
			"goosed",
			"fingered",
			"banged",
			"fucked",
			"bit",
            "drove",
            "loved",
            "hurt",
            "groaned",
            "moaned",
            "screamed",
            "sighed",
            "sobbed",
            "begged",
],
		
		verbing: [
"kissing",
			"hugging",
			"groping",
			"licking",
			"touching",
			"goosing",
			"fingering",
			"banging",
			"fucking",
			"biting",
            "driving",
            "loving",
            "hurting",
            "groaning",
            "moaning",
            "screaming",
            "sighing",
            "sobbing",
            "begging",
],
		
		   
		verb: [
"kiss",
			"hug",
			"grope",
			"lick",
			"touch",
			"goose",
			"finger",
			"bang",
			"fuck",
			"bite",
            "drive",
            "love",
            "hurt",
            "groan",
            "moan",
            "scream",
            "sigh",
            "sob",
            "beg",
],
		
				   
		bodypart: [
"tongue",
			"ear",
			"mouth",
			"finger",
			"hand",
			"foot",
			"pussy",
			"cock",
			"dick",
			"devil's doorbell",
            "body",
            "tooth",
            "skin",
            "hair",
            "eyes",
            "toes",
            "nose",
            "lips",
            "pecs",
            "arms",
            "legs",
            
],
		
locations: [
			"closet",
			"office",
			"garage",
			"bed",
			"boat",
			"canoe",
			"car",
			"movie theater",
			"classroom",
			"teacher's office",
            "sea",
            "sun",
            "bedroom",
            "kitchen",
            "bathroom",
            "nightclub",
		]
noun: [
    "perfume",
    "dildo",
    "vibrator",
    "dog",
    "cat",
    "table",
    "car",
    "cup",
    "glass",
    "river",
    "chariot",
    "man",
    "woman",
    "bed",
    "desk",
    "chair",
    "smoke",
    "fire",
    ]
    
fluid: [
    "sweat",
    "spit",
    "wine",
    "beer",
    "water",
    "saliva",
    "juice",
    "liquor",
    "coffee",
    "tea",
    "milk",
    ]    
 });

// Populate using a JSON file
//WTF.init( 'sample.json' );

// Populate using a Google spreadsheet ID (you must publish it first!)
// @see https://support.google.com/drive/answer/37579?hl=en
// WTF.init( '0AvG1Hx204EyydF9ub1M2cVJ3Z1VGdDhTSWg0ZV9LNGc' );
// WTF.init( '1ETfPSeCQJoLRRkqQQ6b8P4hvVJ8UrXbuNFZ9SRUqOsA' );
// WTF.init( '2PACX-1vR-vpMhRmASTY0RAud6t_WEWfHjsqCaBOL0JmklB2kEStUS5ChzDewI64ncJjaKOxeP6ufa0vFlNpkx' );
});
